################################################################################
#
#   CONFIGURATION FILE
#   This file contains all of the configuration options for the game.
#   You can change these options to customize the game to your liking.
#
#   Note: If you decide to use a custom config.yaml, it is recommended that you
#   copy only the properties you want to change of this file into your own 
#   config.yaml.
#   When running the server, use the environment variable: CONFIG_PATH like so: 
#   CONFIG_PATH=../mudfiles/config.yaml to specify where your custom config file
#   can be found. 
#
#   This way when you update the server, your custom config file will not be
#   overwritten.
#
################################################################################
################################################################################
#
#   FILE AND FOLDER CONFIGURATIONS
#   If you want to customize some of this data, for whatever reason,
#   you can change the folder paths here so that future updates don't
#   overwrite your changes.
#
################################################################################
# - Version - 
#   Latest semantic version of the datafiles (MAJOR.MINOR.PATCH)
#   Do not change this value, it will be handled by the server when updated
#   MAJOR version - incompatible API changes. Will attempt to upgrade datafiles.
#   MINOR version - added functionality (backward compatible)
#   PATCH version - bug fix (backward compatible)
Version: "1.0.0"
# - FolderUserData - 
#   Relative path to where the user datafiles are stored - set to a folder
#   outside of the repo to preserve your user data files.
FolderUserData: _datafiles/users 
# - FolderTemplates -
#   Templates define all sorts of display rules
FolderTemplates: _datafiles/templates 
# - FolderItemData -
#   Where the item datafiles are stored
FolderItemData: _datafiles/items 
# - FolderItemData -
#   Where spell datafiles are stored
FolderSpellData: _datafiles/spells
# - FolderAttackMessageData -
#   Defines the various combat related text messages
FolderAttackMessageData: _datafiles/combat-messages 
# - FolderRoomData -
#   Maps common aliases to specific ansi color codes
FileAnsiAliases: _datafiles/ansi-aliases.yaml 
# - FileKeywords -
#   Keywords are used to match commands to actions
#   Also used for aliases
FileKeywords: _datafiles/keywords.yaml
# - AllowItemBuffRemoval - 
#   Whether to allow the removal of buffs assigned by items using spells etc. 
#   By default, once an item has buffed a player, the player cannot remove the 
#   buff unless they removing the item. However, if set to true, players can 
#   temporarily remove the buff with spells, items, etc. and the buff will not 
#   return until the player re-equips the item, or logs out and back in.
AllowItemBuffRemoval: false
# - CarefulSaveFiles -
#   If true, save files will be written to a temporary file and then saved over
#   the actual file. This takes longer, but helps prevent file corruption if
#   the server crashes during a save.
CarefulSaveFiles: true
################################################################################
#
#   GAMEPLAY CONFIGURATIONS
#   These modify the way the game players, the pace/speed of the game, etc.
#
################################################################################
# - AuctionsEnabled -
#   If true, players can globally auction off items.
AuctionsEnabled: true
# - AuctionsAnonymous -
#   If true, seller/buyer names are not revealed.
AuctionsAnonymous: false
# - AuctionSeconds -
#   How may seconds until an auction closes.
AuctionSeconds: 180
# - AuctionUpdateSeconds -
#   How may seconds (roughly) between updates on current auction.
AuctionUpdateSeconds: 30
# - PVPEnabled -
#   If true, players can attack each other. If false, they cannot.
PVPEnabled: true
# - XPScale -
#   Scales XP Charts for character leveling. Lower means less required, higher
#   means more required. 1 is the default (no change).
XPScale: 1
# - TurnMs -
#   How many milliseconds per turn. While lower is generally better, this can
#   greatly increase overhead on the server - a command per mob or user is
#   processed per turn. This is not the same as rounds, which is how often the
#   mobs choose their actions, but if multiple actions are queued up, they will
#   be processed in order once per turn. 
#   The effect of this can be easily seen in the initial login to the game,
#   where several commands are queued up at once and processed in order for the 
#   player.
#   100 is a good balance between handling input from players and not bogging
#   down the server.
TurnMs: 100
# - RoundSeconds - 
#   How many seconds per round. Anything gated by rounds will be affected by
#   this. This is the main setting for controlling the pace of the game.
RoundSeconds: 4
# - OnDeathEquipmentDropChance -
#   The chance that a player will drop a piece of worn/backpack equipment when 
#   they die. This is a percentage, so 0.5 is 50% chance.
OnDeathEquipmentDropChance: 0.25
# - OnDeathAlwaysDropBackpack -
#   If true, players will always drop their backpack contents when they die. 
#   If false, it will failover to OnDeathEquipmentDropChance.
OnDeathAlwaysDropBackpack: false
# - OnDeathXPPenalty -
#   What penalty is applies to a players XP when they die.
#   none - no penalty
#   level - lose all XP gained over their current level.
#   10% - lose 10% of XP
#   50% - lose 50% of XP
OnDeathXPPenalty: none
# - EnterRoomMessageWrapper -
#   Decorate entrance text with this. Put a %s where the message should be.
EnterRoomMessageWrapper: "   <ansi fg=\"enters-message\"> >>> </ansi>%s"
# - ExitRoomMessageWrapper -
#   Decorate exit text with this. Put a %s where the message should be.
ExitRoomMessageWrapper: "   <ansi fg=\"leaves-message\"> >>> </ansi>%s"
# - MaxIdleSeconds -
#   How long players can go without any input, before being kicked.
#   A value of 0 (zero) means never kick inactive players.
#   900 seconds = 15 minutes
MaxIdleSeconds: 900
# - ZombieSeconds -
#   How many seconds a character stays active/in game after a network connection
#   is lost. Set to 0 to instantly log out characters (exploitable).
ZombieSeconds: 30
# - LogoutRounds - 
#   How many rounds of meditation a player must complete before they are
#   logged out. If interrupted, they must start over.
LogoutRounds: 3
# - TutorialStartRooms - 
#   RoomIds players will be put in when starting the game/tutorial
#   RoomIds 900-999 are reserved for Tutorial rooms.
TutorialStartRooms: [900, 990]
# - PermaDeath - 
#   If true, players lose their character if they die with zero lives left.
PermaDeath: true
# - StartLives - 
#   (Req: PermaDeath) Hhow many lives players start with before being reset.
StartLives: 3
# - MaxLives - 
#   (Req: PermaDeath) The maximum lives a player can have.
MaxLives: 3
# - LevelUpLives -
#   (Req: PermaDeath) If non zero, players gain this many lives per level.
LevelUpLives: 1
# - PricePerLife - 
#   (Req: PermaDeath) If non-zero, players can buy extra lives for this amount.
PricePerLife: 1000000
# - ShopRestockRounds - 
#   The default number of rounds shops take to restock 1 item. This can still be 
#   overriden in character shop definitions if desired.
ShopRestockRounds: 75
# - ConsistentAttackMessages - 
#   If true, each weapon will consistently use the same message for each type of
#   attack. If false, it will randomize the messages. Setting this to true gives
#   each weapon a more unique feel in battle, but combat may feel less varied.
#   Note: see _datafiles/combat-messages/* to see/add weapon type messages.
ConsistentAttackMessages: true
################################################################################
#
#   MEMORY/CPU OPTIMIZATIONS
#   Changes that can help reduce memory and CPU usage.
#
################################################################################
# - MaxCPUCores -
#   Maximum CPU cores to use. 0 for all available cores.
#   Most of the game is single threaded, but there are a few things that can
#   benefit from multiple cores, such as the web server and telnet server.
MaxCPUCores: 0
# - RoundsPerAutoSave -
#   How often the server will automatically save the game state. This is a
#   backup feature in case the server crashes. The game state is also saved
#   whenever the server is shut down.
RoundsPerAutoSave: 900
# - MaxMobBoredom -
#   How many rounds a mob can go without seeing a player before a mob despawns. 
#   This is mainly a resource management feature to keep the game from getting 
#   bogged down with too many mobs in memory. If you want mobs to stick around 
#   indefinitely, set this to 0. Certain mobs may never despawn, however.
MaxMobBoredom: 150
# - RoundsPerDay -
#   How many rounds are in a day? This is used to calculate the time of day.
#   The lower this number, the faster the day/night cycle will be.
#   A 4 second round and a 900 round day means the day/night cycle is 1 hour.
RoundsPerDay: 900
# - NightHours -
#   How many hours of each 24 hour day will be nighttime?
NightHours: 8
# - ScriptLoadTimeoutMs -
#   When a script is first loaded, compiled, and run, it is given this long to
#   complete. If it takes longer, it is killed. This includes the onLoad() function
#   in scripts. Allowing a script to take longer to load might be okay to prepare some
#   heavier data.
ScriptLoadTimeoutMs: 1000
# - ScriptRoomTimeoutMs - 
#   How long a room script can run before it is killed. This is a safety feature to
#   prevent long running scripts from bogging down the server.
ScriptRoomTimeoutMs: 10
################################################################################
#
#   NETWORK SETTINGS
#   Custom network settings for the server. If you are running the server
#
################################################################################
# - MaxTelnetConnections - 
#   The maximum number of telnet connections the server will accept.
MaxTelnetConnections: 50
# - TelnetPort -
#   The port the server listens on for telnet connections. Listen on multiple 
#   ports by separating them with commas. For example, "33333,33334,33335"
TelnetPort: 33333,44444
# - LocalPort -
#   A port that can only be accessed via localhost, but will not limit based on connection count
LocalPort: 9999
# - WebPort -
#   The port the server listens on for web requests
WebPort: 80
################################################################################
#
#   LOOT GOBLIN CONFIGURATIONS
#   This is a special mob that cleans up items and gold left on the ground.
#   It portals in from a special zone and when it can't find any items or gold
#   to pick up, it portals back.
#   Players can actually chase the goblin to its realm and possibly find some
#   treasure.
#
################################################################################
# - LootGoblinRoundCount -
#   How often the Loot Goblin will spawn. It is a good idea to keep this 
#   number low to keep the game from getting bogged down with too many items 
#   on the ground. At 4 seconds per round, 900 rounds is 1 hour.
LootGoblinRoundCount: 900
# - LootGoblinMinimumItems -
#   How many items there must be on the room to attract the loot goblin
LootGoblinMinimumItems: 2
# - LootGoblinMinimumGold -
#   How much gold there must be on the room to attract the loot goblin
LootGoblinMinimumGold: 100
# - LootGoblinIncludeRecentRooms -
#   If true, the loot goblin will also clean recently visited by players rooms 
#   If allowed, this could create a situation where a lot of loot drops and the 
#   suddenly the goblin shows up.
LootGoblinIncludeRecentRooms: false
################################################################################
#
#   SERVER CUSTOMIZATIONS
#   Small changes such as login commands and the seed can ensure your mud has
#   differences from others on the same code base.
#
################################################################################
# - Seed -
#   The seed used for certain types of content generation
#   To prevent certain secrets or content from being spoiled, you can set this
#   to a random string.
#   Note: Once the Mud has been played and data saved, changing this will
#   probably break certain things that get saved to files, such as user KeyRings, 
#   so only set it before the first time you run the server.
Seed: "Mud"
# - OnLoginCommands -
#   Commands to run when a user logs in. These commands are run by the user
#   and can be anything they have access to.
OnLoginCommands:
- 'emote @appears before you in a flash of <ansi fg="yellow-bold">⚡l<ansi fg="white-bold">i</ansi>gh<ansi fg="white-bold">tn</ansi>i<ansi fg="white-bold">n</ansi>g⚡</ansi>!'
- print
- motd 
- print
- online
- print 
# - Motd -
#   Message of the day. This is displayed when the motd command is run.
Motd: Welcome to the Mud!
# - BannedNames -
#   Names that are not allowed to be used by players. This is a good place to
#   put names that are used by the game itself, such as "admin".
#   Note: This is not case sensitive.
#   You can add a * to the end of a name to ban all names that start with that
#   name. For example, "admin*" would ban "admin", "administrator", etc.
#   You can also use * at the beginning of a name to ban all names that
#   end with that name. For example, "*admin" would ban "admin", "superadmin",
#   Finally, you can use * at the beginning and end of a name to ban all names
#   that contain that name. For example, "*admin*" would ban "admin", "superadmin",
#   "administrator", etc.
BannedNames:
- "*admin*"
- "*moderator*"
- "player*"
- "user*"
- "me"
- "us"
- "you"
- "them"
- "party"
- "everyone"
- "someone"
- "anyone"
- "nobody"
- "somebody"
- "anybody"
- "none"
- "nothing"
- "something"
- "anything"
- "everything"
- "all"
- "north*"
- "south*"
- "east*"
- "west*"
- "up"
- "down"
- "chest"
- "door"
# - NextRoomID -
# This number is auto-updated to the highest number of rooms in the game. 
#   If creating your own rooms but don't want to risk an update conflicting, 
#   update this to a large number (like 100000), so that as new rooms are 
#   created they will be far beyond the range of any room id's expected through
#   a code update.
NextRoomId: 1001
# - LogIntervalRoundCount - 
#   How often to log the round count. Can help judge logs a little better.
LogIntervalRoundCount: 1
# - Locked -
#   All config names defined here are immutable to the `server set` admin 
#   command. They can only be changed by editing the config file directly.
#   It is a good idea to lock configs related to folder/file paths to prevent
#   accidental changes that could break the game.
Locked: 
- FolderUserData
- FolderTemplates
- FolderItemData
- FolderAttackMessageData
- FileAnsiAliases
- NextRoomId
- Seed
- OnLoginCommands
- BannedNames

################################################################################
#
#   ChatGPT Configurations
#
################################################################################
# - ChatGPTKey - 
#   Your OpenAI Key. If empty, will not use ChatGPT.
ChatGPTKey: ''
