################################################################################
# If modified, these settings will be copied into your config overrides 
# folder under `Plugins.Settings.auctions`:
#
# Plugins:
#   Settings:
#     auctions:
#       Anonymous: false
#       DurationSeconds: 12
#       Enabled: true
#       UpdateSeconds: 30
################################################################################
# - Enabled -
#   If true, players can globally auction off items.
Enabled: true
# - Anonymous -
#   If true, seller/buyer names are not revealed.
Anonymous: false
# - DurationSeconds -
#   How may seconds until an auction closes.
DurationSeconds: 180
# - UpdateSeconds -
#   How may seconds (roughly) between updates on current auction.
UpdateSeconds: 30
