name: run-tests

# on:
#   pull_request:
#     branches: [master]
#   workflow_dispatch:

on:
  push:
    branches: [pre-merge-testing]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run tests
        run: go test ./...
